### ISSUE TITLE
UTM doesn't pass on when we add form with plugin on https website

### ISSUE THREAD

**Issue by zerda-digital** [Pardot/pardot-for-wordpress#14]
Hi, 

We use the pardot plugin on tracktik.com and we are now using UTM in our campaigns. We noticed that we don't get the UTM showing on the prospect profile, on the google analytics section when use the plugin to integrate the form.

Instead if we embed the form using the iframe script and replace the defaut http url  "http://www2.tracktik.com/" with https://go.pardot/ the UTM infos are showing on the profile page on pardot. 

Is there a way to replace by default our default http domain by https://go.pardot ? The best way would be to have a checkbox for https when users have https sites. 

Thxs

**Comment by logoscreative** [comment]
Hi @zerda-digital,

There's a checkbox on the settings page that does exactly what you're asking for: check "Use HTTPS?". Let me know if that doesn't solve it for you.
