### ISSUE TITLE
Pardot iFrame jQuery being blocked on secure sites

### ISSUE THREAD

**Issue by kbrookes** [Pardot/pardot-for-wordpress#18]
This one's a bit odd.

My client's WP site is set for https, the Pardot plugin has the https checkbox enabled and all links to pardot.com in the iFrame are using https... but there's one link that isn't.

jQuery is loaded via "//code.jquery.com/jquery-1.11.3.min.js" - which would normally work whether it's secure or not, but all browsers are giving me a similar message to this:

Blocked loading mixed active content “http://code.jquery.com/jquery-1.11.3.min.js”

As a result the form is lacking placeholders/labels and styles.

I'm not sure why the // trick wouldn't work when it's in an iFrame... 

Any ideas how to resolve this one?

**Comment by logoscreative** [comment]
@kbrookes Any way you could link me to it?

**Comment by kbrookes** [comment]
@logoscreative sure!

https://www.northquest.com.au/contact/

You can also see it in action directly on Pardot's standalone form URLs:

https://go.pardot.com/l/223232/2016-08-23/2j1

vs

http://go.pardot.com/l/223232/2016-08-23/2j1

So it does't seem to be limited to the WP plugin - not sure how 'official' this plugin is. I'm raising a ticket with Pardot support today, but thought that if the team on this repo were in contact with Pardot it might go a little faster.

K

**Comment by logoscreative** [comment]
Ah. Try going into Pardot to edit the form or layout template (can't remember which off the top of my head) and look for `<base href="http://go.pardot.com">`. Change to `<base href="https://go.pardot.com">`.

**Comment by kbrookes** [comment]
Thanks @logoscreative - no dice I'm afraid. The line appeared to be:

const POST_ROOT_URL = 'http://go.pardot.com';

Which I changed to be https instead.

The issue doesn't seem to be related to the base pardot URL, but instead to the jquery CDN URL.

Normally using // instead of http/https works fine as a catch-all in case of cases where the URL can appear in secure or insecure environments, but there seems to be something problematic about its implementation with Pardot; If you look at the go.pardot URLs I provided above you'll see it occurring there also.

**Comment by logoscreative** [comment]
I'm not sure what that's referring to, but are you able to locate `<base href="http://go.pardot.com">` within the form's landing page template? This overrides the relative URL for the iframe, which is why // would be reverting to HTTP.
