### ISSUE TITLE
Many mcrypt deprecation notices on multiple pages

### ISSUE THREAD

**Issue by rask** [pardot/pardot-for-wordpress#20]
With a recent PHP version (e.g. 7.1.) this plugin generates many notices regarding mcrypt deprecation. This spams logs and error aggregation systems needlessly. Would it be possible to swap the mcrypt implementation to some other alternative? I presume you can achieve the same results with sodium?

**Comment by logoscreative** [comment]
Trying to get back up to date on these issues, so my apologies for the egregiously delayed reply.

We check for `openssl_decrypt` now and bail if it's there. Are you still seeing notices in your logs?

**Comment by rask** [comment]
Heh, switched employers and all in between, and am not working with this plugin anymore. But I presume that check should work OK. I think we added some filters to our log settings that suppressed the deprecation warnings as a quick fix back then.

Thanks in any case!
