### ISSUE TITLE
Inline Form markup broken (after reload)

### ISSUE THREAD

**Issue by jerome-toole** [pardot/pardot-for-wordpress#24]
I posted this in the plugin directory but adding here as well as I've since tested with fresh install, theme, form and template and the error is still there which suggests it can't be anything to do with our setup and must be a bug.

I’m using the inline form option `(define( 'PARDOT_FORM_INCLUDE_TYPE', 'inline' );)` in the plugin in order to be able to use certain tracking features.

It seems to work on the first load but on subsequent loads, the scripts in the head are misconfigured and sometimes the html is exposed as text. The result is that the correct scripts aren’t loaded and so the form fails. If I clear the cache and reload, the form loads correctly again.

One of the script tags is pointing to an obviously wrong src
```
<script type="text/javascript" src="https://go.pardot.com/customer/en/portal/articles/2126621-default-form-style-classes-reference type=" text="" javascript"="">
```

There are the following console errors:
```
2126621-default-form-style-classes-reference%20type=:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1421 Uncaught SyntaxError: Invalid or unexpected token
(index):1429 Uncaught ReferenceError: pardot is not defined
```

On testing with a fresh form (including the standard form styling), the markup is slightly different but still broken:
![image](https://user-images.githubusercontent.com/5527867/46214922-0eded380-c334-11e8-86e0-8c9786f2f948.png)

**Comment by logoscreative** [comment]
Trying to get back up to date on these issues, so my apologies for the egregiously delayed reply.

Looks like we resolved this issue over in the forums: https://wordpress.org/support/topic/inline-form-markup-breaks-after-reload/
