### ISSUE TITLE
Dynamic shortcode does not work

### ISSUE THREAD

**Issue by jonathan-dejong** [pardot/pardot-for-wordpress#26]
Hi!

I posted in the WP forum as well but hope there's faster responses here! 

Just setup the plugin and authenticated but I can’t get the dynamic shortcode `[pardot-dynamic-content id=""]` to work. The “static” iframe shortcode `[pardot-form id=""]` works with the same ID.
There’s no debugging information at all, no errors.. It just outputs an empty `<noscript></noscript>` (not even with the default content even if I set that in the shortcode directly).
So I’m thinking that there’s three possibilities:
1. I’m missing something that needs to be setup in the pardot admin
2. The dynamic shortcode does not work on a local dev site because your service needs to ping back to the server (?)
3. Something is broken in the plugin.

Gladly accept any help in the matter!

EDIT:
I’ve also tried it with an ngrok URL just to test wether (2.) above is the culprit but it’s the same thing.. so I’m guessing the dev server isn’t the issue.

**Comment by logoscreative** [comment]
Closing this for now after no reply over in the forums: https://wordpress.org/support/topic/dynamic-shortcode-does-not-work/

Let me know if you're still having this issue.
