### ISSUE TITLE
Server crash becouse the daily api rate limit

### ISSUE THREAD

**Issue by AndrejGen** [pardot/pardot-for-wordpress#30]
Hi,

the plugin calls the Pardot_API::get_response() function recursively when the error message
[Daily API rate limit met](http://developer.pardot.com/kb/error-codes-messages/#error-code-122) is returned.

Maybe the plugin should pass the error message to the server in this case.

**Comment by logoscreative** [comment]
Thank you, @AndrejGen! I'm in the process of refactoring a number of functions—one major item that needs updating is handling errors from the server. the Pardot API didn't even offer a number of these responses when these were written years ago.

**Comment by efishinsea** [comment]
Did this issue get fixed?  We've experienced this too, and it results in the site crashing.

**Comment by logoscreative** [comment]
@AndrejGen @efishinsea If you're able to access the plugin files directly, can you update line 467 in `includes/pardot-api-class.php` to:

`if ( $this->authenticate( $auth ) && 'Daily API rate limit met.' !== $response->err ) {`

This _should_ bail on the recursion aspect.
