### ISSUE TITLE
Latest Release doesn't compile on wordpress.com server

### ISSUE THREAD

**Issue by creuzerm** [pardot/pardot-for-wordpress#36]
The latest publish breaks the entire wordpress install on wordpress.com hosting. This is the error I get. Busy trying to roll-back Pardot plugin for now before I dive in and debug.

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 61 of the file /srv/htdocs/wp-content/plugins/pardot/pardot.php. Error message: require(): Failed opening required '/srv/htdocs/wp-content/plugins/pardot/includes/pardot-crypto.php' (include_path='/:.')

**Comment by logoscreative** [comment]
Hey @creuzerm, thanks for the report. Can you try updating with a fresh copy? There was about 10 minutes of the plugin being released where one of the files (pardot-crypto.php) wasn’t in the WP repository properly.

**Comment by creuzerm** [comment]
The re-install has me back up and running. Thanks!

Testing. I don't have activity tracking yet, but I may be having login issues.

**Comment by creuzerm** [comment]
Reinstalling resolved issue.  Thank you for the proof prompt response.

**Comment by logoscreative** [comment]
Thank you for following up, @creuzerm! 🍻
