### ISSUE TITLE
Form embedCode: Give option to use https://go.pardot.com, rather than http://cname.company.com

### ISSUE THREAD

**Issue by jeffelrod** [Pardot/pardot-for-wordpress#5]
For clients who have https secured sites, or automatic http -> https rewriting set up in such a way that forms' iframe URLs are converted from http://cname.company.com to https://cname.company.com, we should allow an option to use the https://go.pardot.com URL for forms. When the user is selecting a form, it could just be a checkbox that says something like "use secure URL." It'd be a simple string replace on the $form->embedCode. See: https://pardot.atlassian.net/browse/IDEA-1000. #solutionsswarm

**Comment by Benjaki2** [comment]
@jeffelrod I need this! Has any movement been made?

**Comment by jeffelrod** [comment]
Hi @Benjaki2 - this actually went live in a December 9, 2014 update, just didn't remember to close this issue! From Settings > Pardot, you can choose to embed HTTPS forms.

**Comment by RCooLeR** [comment]
http://letzgro.net/blog/pardot-salesforce-marketing-automation-solution-how-to-ssl-enable-http-secure-urls/
