### ISSUE TITLE
Too many calls to pi.pardot.com

### ISSUE THREAD

**Issue by jbrass** [Pardot/pardot-for-wordpress#7]
I am noticing calls a ton of calls to pi.pardot.com on almost every request in wordpress. Reading the code it looks like the plugin is using the internal wordpress cache but I am still seeing tons of calls to pi.pardot.com. Is this normal? Shouldn't this information be in the cache. 

![screen shot 2015-03-06 at 4 07 17 pm](https://cloud.githubusercontent.com/assets/125982/6538775/7b70e996-c41b-11e4-90e7-e7bdb88a9b62.png)

Is this expected behaviour?

**Comment by teran-mckinney** [comment]
We are also seeing this. What's the recommended fix?

It appears it blocks the whole page load and this is not asynchronous at all. Each page load is blocked by the call to Pardot and back. if you ever go down, any site using this probably will, too.

**Comment by logoscreative** [comment]
I'm sorry for the delay here! I'm not sure why GitHub decided to never notify me of some of these Issues last year, but here were are. :)

Have either of you contacted supported and asked there? The plugin only uses the methods of tracking we recommend to anyone else, so this would most likely not be specific to it.

That said, the plugin does cache certain data from our API, but all the functionality is still going to ping Pardot on each page load—for campaign tracking, or for the form's iframe, or for dynamic content's JS file.
