### ISSUE TITLE
Inline includes

### ISSUE THREAD

**Issue by jayato3** [Pardot/pardot-for-wordpress#8]
I noticed you can define 'PARDOT_FORM_INCLUDE_TYPE' as inline to get an inline form. Can you shed any light on this feature? What functionality is missing form the iframe include type?

**Comment by logoscreative** [comment]
I'm sorry for the delay here! I'm not sure why GitHub decided to never notify me of some of these Issues last year, but here were are. :)

That definition was part of an experimental feature being considered early on in the plugin. As it sits, it's not a beneficial way to use Pardot forms, so it's not documented.
