### ISSUE TITLE
Forms don't work on sites using HTTPS where host name doesn't end in 2 or 3 characters 

### ISSUE THREAD

**Issue by mjlodge** [Pardot/pardot-for-wordpress#9]
Hi there,

We use the .works TLD for our website, https://www.weave.works/

We noticed that the Pardot Widget for forms worked just fine if we turned off https. When we turned https on, then the iframe URL for the Pardot form got mangled by the plug-in (and so wouldn't display). This was a mystery to us until I finally looked at the code for the plugin and noticed that the RegEx used to form a https://go.pardot.com URL when a site runs under SSL assumes that the domain name ends in two or three characters:

pardot-plugin-class.php, line 635:
`$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";`

The {2,3} is the give-away. It says the domain name has to end in 2 or 3 characters, like .uk or .com. Well, that hasn't been the case for top level domains for some time...

Our Domain Tracker was go.weave.works. When you use that RegEx and prepend it with "https://go.pardot.com" as the code does on lines 636-641, you get

`https://go.pardot.comks/<rest of URL goes here>`

The RegEx should probably be something like

`/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+(\/\S*)?/`

This just does a simple match of any domain name before a forward slash and the rest of the URL.

**Comment by logoscreative** [comment]
@mjlodge Thanks for the clear layout of the issue. To confirm, weave.works has been successfully saved and utilized inside Pardot as a tracker domain already, correct?

**Comment by mjlodge** [comment]
Yes, correct.

**Comment by RCooLeR** [comment]
http://letzgro.net/blog/pardot-salesforce-marketing-automation-solution-how-to-ssl-enable-http-secure-urls/

**Comment by mjlodge** [comment]
Yeah,@rcooler, but that isn't the problem we had. The problem is not that we can't use a custom domain name. It's that the plugin gets the https URL wrong entirely.

**Comment by lezgro** [comment]
You can fix it fast in next way.

```
/**
 * Replace data in output HTML code
 * 
 * @param string $buffer
 * @return string
 */
function far_ob_call($buffer)
{
    // $buffer contains entire page
    $buffer = str_replace('//go.pardot.com', '//content.decisionresourcesgroup.com', $buffer);
    return $html;
}

/**
 * Add filter for output HTML code
 */
function far_template_redirect()
{
    ob_start();
    ob_start('far_ob_call');
}
add_action('template_redirect', 'far_template_redirect');
```

**Comment by mjlodge** [comment]
Or I could fix the regex, which is what I did.

**Comment by lezgro** [comment]
For sure that was the best solution!

**Comment by mjlodge** [comment]
I do like your solution, BTW -- very handy for when you want to use your own domain.

**Comment by RCooLeR** [comment]
That's only way to do that with https.

**Comment by logoscreative** [comment]
I made a couple of tweaks I'd like to get tested before release.

Please download the 1.4.1 branch (also PR #11) to see if things work for you. I'll release officially soon if so. Thanks!
